'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
'
Namespace GALAServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClientsData", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Partial Public Class ClientsData
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private ClasificacionIndustriaField As String
        
        Private CodClaseField As String
        
        Private CodEmpleadoField As Integer
        
        Private CodGrupoField As Integer
        
        Private CodPaisField As String
        
        Private DireccionCobroField As String
        
        Private DireccionEnviarField As String
        
        Private EmailField As String
        
        Private FaxField As String
        
        Private FechaAperturaField As Date
        
        Private FechaModificacionField As Date
        
        Private NombreField As String
        
        Private NombreFactField As String
        
        Private ObservacionesField As String
        
        Private TelefonoField As String
        
        Private TerField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClasificacionIndustria() As String
            Get
                Return Me.ClasificacionIndustriaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClasificacionIndustriaField, value) <> true) Then
                    Me.ClasificacionIndustriaField = value
                    Me.RaisePropertyChanged("ClasificacionIndustria")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodClase() As String
            Get
                Return Me.CodClaseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodClaseField, value) <> true) Then
                    Me.CodClaseField = value
                    Me.RaisePropertyChanged("CodClase")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodEmpleado() As Integer
            Get
                Return Me.CodEmpleadoField
            End Get
            Set
                If (Me.CodEmpleadoField.Equals(value) <> true) Then
                    Me.CodEmpleadoField = value
                    Me.RaisePropertyChanged("CodEmpleado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodGrupo() As Integer
            Get
                Return Me.CodGrupoField
            End Get
            Set
                If (Me.CodGrupoField.Equals(value) <> true) Then
                    Me.CodGrupoField = value
                    Me.RaisePropertyChanged("CodGrupo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodPais() As String
            Get
                Return Me.CodPaisField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodPaisField, value) <> true) Then
                    Me.CodPaisField = value
                    Me.RaisePropertyChanged("CodPais")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DireccionCobro() As String
            Get
                Return Me.DireccionCobroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DireccionCobroField, value) <> true) Then
                    Me.DireccionCobroField = value
                    Me.RaisePropertyChanged("DireccionCobro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DireccionEnviar() As String
            Get
                Return Me.DireccionEnviarField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DireccionEnviarField, value) <> true) Then
                    Me.DireccionEnviarField = value
                    Me.RaisePropertyChanged("DireccionEnviar")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fax() As String
            Get
                Return Me.FaxField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaxField, value) <> true) Then
                    Me.FaxField = value
                    Me.RaisePropertyChanged("Fax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaApertura() As Date
            Get
                Return Me.FechaAperturaField
            End Get
            Set
                If (Me.FechaAperturaField.Equals(value) <> true) Then
                    Me.FechaAperturaField = value
                    Me.RaisePropertyChanged("FechaApertura")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaModificacion() As Date
            Get
                Return Me.FechaModificacionField
            End Get
            Set
                If (Me.FechaModificacionField.Equals(value) <> true) Then
                    Me.FechaModificacionField = value
                    Me.RaisePropertyChanged("FechaModificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombre() As String
            Get
                Return Me.NombreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreField, value) <> true) Then
                    Me.NombreField = value
                    Me.RaisePropertyChanged("Nombre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreFact() As String
            Get
                Return Me.NombreFactField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreFactField, value) <> true) Then
                    Me.NombreFactField = value
                    Me.RaisePropertyChanged("NombreFact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observaciones() As String
            Get
                Return Me.ObservacionesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionesField, value) <> true) Then
                    Me.ObservacionesField = value
                    Me.RaisePropertyChanged("Observaciones")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Telefono() As String
            Get
                Return Me.TelefonoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelefonoField, value) <> true) Then
                    Me.TelefonoField = value
                    Me.RaisePropertyChanged("Telefono")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ter() As Integer
            Get
                Return Me.TerField
            End Get
            Set
                If (Me.TerField.Equals(value) <> true) Then
                    Me.TerField = value
                    Me.RaisePropertyChanged("Ter")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="GALAServiceReference.IGALAService")>  _
    Public Interface IGALAService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGALAService/GetAllClients", ReplyAction:="http://tempuri.org/IGALAService/GetAllClientsResponse")>  _
        Function GetAllClientsAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of GALAServiceReference.ClientsData))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IGALAServiceChannel
        Inherits GALAServiceReference.IGALAService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GALAServiceClient
        Inherits System.ServiceModel.ClientBase(Of GALAServiceReference.IGALAService)
        Implements GALAServiceReference.IGALAService
        
        ''' <summary>
        ''' Implement this partial method to configure the service endpoint.
        ''' </summary>
        ''' <param name="serviceEndpoint">The endpoint to configure</param>
        ''' <param name="clientCredentials">The client credentials</param>
        Partial Private Shared Sub ConfigureEndpoint(ByVal serviceEndpoint As System.ServiceModel.Description.ServiceEndpoint, ByVal clientCredentials As System.ServiceModel.Description.ClientCredentials)
        End Sub
        
        Public Sub New()
            MyBase.New(GALAServiceClient.GetDefaultBinding, GALAServiceClient.GetDefaultEndpointAddress)
            Me.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGALAService.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration)
            MyBase.New(GALAServiceClient.GetBindingForEndpoint(endpointConfiguration), GALAServiceClient.GetEndpointAddress(endpointConfiguration))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As String)
            MyBase.New(GALAServiceClient.GetBindingForEndpoint(endpointConfiguration), New System.ServiceModel.EndpointAddress(remoteAddress))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(GALAServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAllClientsAsync() As System.Threading.Tasks.Task(Of System.Collections.ObjectModel.ObservableCollection(Of GALAServiceReference.ClientsData)) Implements GALAServiceReference.IGALAService.GetAllClientsAsync
            Return MyBase.Channel.GetAllClientsAsync
        End Function
        
        Public Overridable Function OpenAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndOpen)
        End Function
        
        Public Overridable Function CloseAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndClose)
        End Function
        
        Private Shared Function GetBindingForEndpoint(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.Channels.Binding
            If (endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IGALAService) Then
                Dim result As System.ServiceModel.BasicHttpBinding = New System.ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = true
                Return result
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetEndpointAddress(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.EndpointAddress
            If (endpointConfiguration = EndpointConfiguration.BasicHttpBinding_IGALAService) Then
                Return New System.ServiceModel.EndpointAddress("http://localhost:49920/Service.svc")
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetDefaultBinding() As System.ServiceModel.Channels.Binding
            Return GALAServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGALAService)
        End Function
        
        Private Shared Function GetDefaultEndpointAddress() As System.ServiceModel.EndpointAddress
            Return GALAServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGALAService)
        End Function
        
        Public Enum EndpointConfiguration
            
            BasicHttpBinding_IGALAService
        End Enum
    End Class
End Namespace
