'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property IdCliente As Integer
    Public Property Nombre As String
    Public Property NombreFact As String
    Public Property DireccionCobro As String
    Public Property DireccionEnviar As String
    Public Property CodPais As String
    Public Property Ter As Nullable(Of Decimal)
    Public Property Telefono As String
    Public Property Fax As String
    Public Property CodEmpleado As Nullable(Of Decimal)
    Public Property FechaApertura As Nullable(Of Date)
    Public Property Email As String
    Public Property CodGrupo As Nullable(Of Decimal)
    Public Property ClasificacionIndustria As String
    Public Property Observaciones As String
    Public Property CodClase As String
    Public Property FechaModificacion As Nullable(Of Date)

    Public Overridable Property Empleado As Empleado
    Public Overridable Property Pais As Pais

End Class
