'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property CodEmpleado As Decimal
    Public Property NombreEmpleado As String
    Public Property Cargo As String
    Public Property FechaAdicion As Nullable(Of Date)
    Public Property FechaInicio As Nullable(Of Date)

    Public Overridable Property Clientes As ICollection(Of Cliente) = New HashSet(Of Cliente)

End Class
