'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pais
    Public Property CodPais As String
    Public Property Nombre As String
    Public Property CodArea As String
    Public Property Region As String
    Public Property Continente As String

    Public Overridable Property Clientes As ICollection(Of Cliente) = New HashSet(Of Cliente)

End Class
